name: Clean Inactive Channels

on:
  schedule:
    - cron: '0 4 * * 0'
  workflow_dispatch:

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run Clean
      env:
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      run: python clean.py