name: YouTube Monitor

on:
  schedule:
    # 每周日凌晨收集潜力频道
    - cron: '0 0 * * 0'
      name: Collect Channels
    # 每天更新频道数据
    - cron: '0 0 * * *'
      name: Update Channels
    # 每周日凌晨4点清理不活跃频道
    - cron: '0 4 * * 0'
      name: Clean Inactive
  workflow_dispatch:      # 手动触发按钮
jobs:
  # collect:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Set up Python
  #     uses: actions/setup-python@v5
  #     with:
  #       python-version: '3.x'
  #   - name: Install dependencies
  #     run: pip install -r requirements.txt
  #   - name: Run Collection
  #     env:
  #       YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
  #       SEARCH_KEYWORDS: ${{ secrets.SEARCH_KEYWORDS }}
  #     run: python collect.py

  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run Update
      env:
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        ALERT_EMAIL: ${{ secrets.ALERT_EMAIL }}
        EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}
      run: python update.py

  clean:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run Clean
      env:
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      run: python clean.py
